---
title: "Enrollment Data"
author: "Andy Wang"
date: "2/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(janitor)
library(gt)
```

```{r gov_top_5, echo=F}
enrollment_stats <- read_excel("enrollment_data.xlsx", skip = 3) %>%
    clean_names("snake")
top_departments <- enrollment_stats %>%
  filter(course_department != "General Education") %>%
  group_by(course_department) %>%
  summarize(sum = sum(total)) %>%
  arrange(desc(sum)) %>%
  slice(1:5) 

spring_19_data <- read_excel("spring_2019.xlsx", skip = 3) %>%
  clean_names("snake")

new_courses <- enrollment_stats %>%
  anti_join(spring_19_data, by = "course_name")

View(new_courses)

top_courses <- new_courses %>%
  right_join(top_departments, by = "course_department") %>%
  group_by(course_department) %>%
  filter(total == max(total)) %>%
  ungroup() %>%
  arrange(desc(total)) %>%
  select(course_title, course_name, course_department, instructor_full_name, total)

top_courses %>%
  gt() %>%
  cols_label(
    course_title = "Course Title",
    course_name = "Course Name",
    course_department = "Course Department",
    instructor_full_name = "Instructor",
    total = "Enrollment"
  ) %>%
  tab_header(title = "Most Popular New Courses in Large Departments"
  ) %>%
  tab_footnote(
    footnote = "Data from Harvard University",
    locations = cells_title(groups = "title")
  ) 
```
